Mirror Play/Areas/V/Controllers/VideosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Mirror_Play.Areas.V.Controllers
{
    public class VideosController : Controller
    {
        // GET: V/Videos
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Video()
        {
            return View();
        }
    }
}

Mirror Play/Controllers/videosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Mirror_Play;

namespace Mirror_Play.Controllers
{
    public class videosController : Controller
    {
        private mirrorplay db = new mirrorplay();

        // GET: videos
        public ActionResult Index()
        {
            return View(db.videos.ToList());
        }

        // GET: videos/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            video video = db.videos.Find(id);
            if (video == null)
            {
                return HttpNotFound();
            }
            return View(video);
        }

        // GET: videos/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: videos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,post_author,post_date,post_date_gmt,post_content,post_title,post_status,comment_status,post_name,post_modified,post_modified_gmt,guid,post_type,post_mime_type,comment_count")] video video)
        {
            if (ModelState.IsValid)
            {
                db.videos.Add(video);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(video);
        }

        // GET: videos/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            video video = db.videos.Find(id);
            if (video == null)
            {
                return HttpNotFound();
            }
            return View(video);
        }

        // POST: videos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,post_author,post_date,post_date_gmt,post_content,post_title,post_status,comment_status,post_name,post_modified,post_modified_gmt,guid,post_type,post_mime_type,comment_count")] video video)
        {
            if (ModelState.IsValid)
            {
                db.Entry(video).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(video);
        }

        // GET: videos/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            video video = db.videos.Find(id);
            if (video == null)
            {
                return HttpNotFound();
            }
            return View(video);
        }

        // POST: videos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            video video = db.videos.Find(id);
            db.videos.Remove(video);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Mirror Play/Areas/V/Views/Videos/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<div class="container videos-container">
    <div class="row videos-featured-container">
        <div class="col-md-4 video-thumbnail">
            <a href="@Url.Action("Video", "Videos", new { area = "V" })">
                <img class="img-responsive responsive" src="https://static-cdn.jtvnw.net/s3_vods/a12b676b0809efe3fa66_spencerkmedia__33932727488_1189450614/thumb/thumb0-320x180.jpg" />
                <div class="thumbnail-title">
                    <p>Video Title</p>
                </div>
                <div class="thumbnail-author">
                    <p>Mark Rober</p>
                </div>
                <div class="thumbnail-stats">
                    <ul class="list-inline list-unstyled">
                        <li class="list-inline-item views">265K Views</li>
                        <li class="list-inline-item">2 hours ago</li>
                    </ul>
                </div>
            </a>
        </div>
        <div class="col-md-4 video-thumbnail">
            <a href="@Url.Action("Video", "Videos", new { area = "V" })">
                <img class="img-responsive responsive" src="https://static-cdn.jtvnw.net/s3_vods/9b08aed8e3396b932173_spencerkmedia__33920060192_1188658457/thumb/thumb0-320x180.jpg" />
                <div class="thumbnail-title">
                    <p>Video Title</p>
                </div>
                <div class="thumbnail-author">
                    <p>Peter McKinnon</p>
                </div>
                <div class="thumbnail-stats">
                    <ul class="list-inline list-unstyled">
                        <li class="list-inline-item views">265K Views</li>
                        <li class="list-inline-item">2 hours ago</li>
                    </ul>
                </div>
            </a>
        </div>
        <div class="col-md-4 video-thumbnail">
            <a href="@Url.Action("Video", "Videos", new { area = "V" })">
                <img class="img-responsive responsive" src="https://static-cdn.jtvnw.net/s3_vods/c88d47edf3503bd12f52_spencerkmedia__33893551280_1187000768/thumb/thumb0-320x180.jpg" />
                <div class="thumbnail-title">
                    <p>Video Title</p>
                </div>
                <div class="thumbnail-author">
                    <p>Casey Neistat</p>
                </div>
                <div class="thumbnail-stats">
                    <ul class="list-inline list-unstyled">
                        <li class="list-inline-item views">265K Views</li>
                        <li class="list-inline-item">2 hours ago</li>
                    </ul>
                </div>
            </a>
        </div>
    </div>
    <div class="row videos-regular-container">
        <div class="col-md-3 video-thumbnail">
            <a href="@Url.Action("Video", "Videos", new { area = "V" })">
                <img class="img-responsive responsive" src="https://static-cdn.jtvnw.net/s3_vods/db3a59961a26eca46809_spencerkmedia__34016762448_1194705278/thumb/thumb0-320x180.jpg" />
                <div class="thumbnail-title">
                    <p>Video Title</p>
                </div>
                <div class="thumbnail-author">
                    <p>Rooster Teeth</p>
                </div>
                <div class="thumbnail-stats">
                    <ul class="list-inline list-unstyled">
                        <li class="list-inline-item views">265K Views</li>
                        <li class="list-inline-item">2 hours ago</li>
                    </ul>
                </div>
            </a>
        </div>
        <div class="col-md-3 video-thumbnail">
            <a href="@Url.Action("Video", "Videos", new { area = "V" })">
                <img class="img-responsive responsive" src="https://static-cdn.jtvnw.net/s3_vods/142bc791d114ad945822_spencerkmedia__33974591120_1192068368/thumb/thumb0-320x180.jpg" />
                <div class="thumbnail-title">
                    <p>Video Title</p>
                </div>
                <div class="thumbnail-author">
                    <p>The King of Random</p>
                </div>
                <div class="thumbnail-stats">
                    <ul class="list-inline list-unstyled">
                        <li class="list-inline-item views">265K Views</li>
                        <li class="list-inline-item">2 hours ago</li>
                    </ul>
                </div>
            </a>
        </div>

        <div class="col-md-3 video-thumbnail">
            <a href="@Url.Action("Video", "Videos", new { area = "V" })">
                <img class="img-responsive responsive" src="https://static-cdn.jtvnw.net/s3_vods/142bc791d114ad945822_spencerkmedia__33974591120_1192068368/thumb/thumb0-320x180.jpg" />
                <div class="thumbnail-title">
                    <p>Video Title</p>
                </div>
                <div class="thumbnail-author">
                    <p>Linus Tech Tips</p>
                </div>
                <div class="thumbnail-stats">
                    <ul class="list-inline list-unstyled">
                        <li class="list-inline-item views">265K Views</li>
                        <li class="list-inline-item">2 hours ago</li>
                    </ul>
                </div>
            </a>
        </div>

        <div class="col-md-3 video-thumbnail">
            <a href="@Url.Action("Video", "Videos", new { area = "V" })">
                <img class="img-responsive responsive" src="https://static-cdn.jtvnw.net/s3_vods/142bc791d114ad945822_spencerkmedia__33974591120_1192068368/thumb/thumb0-320x180.jpg" />
                <div class="thumbnail-title">
                    <p>Video Title</p>
                </div>
                <div class="thumbnail-author">
                    <p>Channel Super Fun</p>
                </div>
                <div class="thumbnail-stats">
                    <ul class="list-inline list-unstyled">
                        <li class="list-inline-item views">265K Views</li>
                        <li class="list-inline-item">2 hours ago</li>
                    </ul>
                </div>
            </a>
        </div>
    </div>
</div>

Mirror Play/Areas/V/Views/Videos/Video.cshtml
@{
    ViewBag.Title = "Video";
}

<div class="container video-page-container">
    <div class="row video-object-container">
        <div class="col-md-12 video-player-container">
            <div class="player">
                <video class="afterglow" id="v_1234" poster="https://res.cloudinary.com/spencer-k-media/video/upload/v1557034095/Lower_Third_1_1080.jpg" width="1920" height="1080" src="http://res.cloudinary.com/spencer-k-media/video/upload/v1557034095/Lower_Third_1.mp4">
                    <source type="video/mp4" src="http://res.cloudinary.com/spencer-k-media/video/upload/v1557034095/Lower_Third_1_1080.mp4" data-quality="hd" />
                    <source type="video/mp4" src="https://res.cloudinary.com/spencer-k-media/video/upload/c_scale,h_720,w_1280/v1557034095/Lower_Third_1_1080.mp4" />
                    <source type="video/webm" src="http://res.cloudinary.com/spencer-k-media/video/upload/v1557034095/Lower_Third_1_1080.webm" data-quality="hd" />
                    <source type="video/webm" src="https://res.cloudinary.com/spencer-k-media/video/upload/c_scale,h_720,w_1280/v1557034095/Lower_Third_1_1080.webm" />
                    <source type="video/ogg" src="http://res.cloudinary.com/spencer-k-media/video/upload/v1557034095/Lower_Third_1_1080.ogg" data-quality="hd" />
                    <source type="video/ogg" src="https://res.cloudinary.com/spencer-k-media/video/upload/c_scale,h_720,w_1280/v1557034095/Lower_Third_1_1080.ogg" />
                </video>
            </div>
            <!--<div class="embed-responsive embed-responsive-16by9 video-player">
        <video id="player" width="640" height="365">
            <source src="http://res.cloudinary.com/spencer-k-media/video/upload/v1557034095/Lower_Third_1.webm" type="video/webm">
            <source src="http://res.cloudinary.com/spencer-k-media/video/upload/v1557034095/Lower_Third_1.ogv" type="video/ogv">
            <source src="http://res.cloudinary.com/spencer-k-media/video/upload/v1557034095/Lower_Third_1.mp4" type="video/mp4">
            <p>
                Your browser doesn't support HTML5 video.
                <a href="videos/mikethefrog.mp4">Download</a> the video instead.
            </p>
        </video>
        <div id="video-controls">
            <button type="button" id="play-pause">Play</button>
            <input type="range" id="seek-bar" value="0">
            <button type="button" id="mute">Mute</button>
            <input type="range" id="volume-bar" min="0" max="1" step="0.1" value="1">
            <button type="button" id="full-screen">Full-Screen</button>
        </div>

    </div>-->
            <div class="container video-content">
                <div class="row">
                    <div class="col-md-8 video-column-8">
                        <ul class="list-inline">
                            <li class="list-inline-item"><img class="author-icon" src="~/Images/usericon.svg" /></li>
                            <li class="list-inline-item"><h2>This Is A Video Title</h2></li>
                        </ul>

                        <h4>707,364 Views</h4>
                    </div>
                    <div class="col-md-4 video-column-4">
                        <ul class="list-inline dist-buttons">
                            <li class="list-inline-item"><i class="fas fa-thumbs-up"></i></li>
                            <li class="list-inline-item"><i class="fas fa-thumbs-down"></i></li>
                            <li class="list-inline-item"><i class="fas fa-share"></i></li>
                            <li class="list-inline-item"><i class="fas fa-list-ul"></i></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>